drop sequence hibernate_sequence;
drop table moves;
drop table games_played;
drop table games_saved;
drop table games;
drop table game_users;
drop trigger testref on users;
drop function insertdata();
drop table authorities;
drop table users;